### ISSUE TITLE
Remove __pycache__ directories from git

### ISSUE THREAD

**Issue by kyleniemeyer** [anthony-walker/pysweep-git#1]
All the `__pycache__` directories should be removed from the Git history, and the project should have a [Python `.gitignore` file](https://github.com/github/gitignore/blob/master/Python.gitignore) added to avoid tracking such files (and other Python-specific output) in the future.

**Comment by anthony-walker** [comment]
.gitignore added. Still need to remove from history.

**Comment by kyleniemeyer** [comment]
It's possible to remove something from the entire Git history, but that's something of a pain in the ass, and probably only worth it for very large files (like MBs). Instead, just do a `git rm __pycache__/*` in each of the directories holding one.

**Comment by anthony-walker** [comment]
This issue should be complete then.
