### ISSUE TITLE
Package needs a LICENSE

### ISSUE THREAD

**Issue by kyleniemeyer** [anthony-walker/pysweep-git#2]
Now that the project is openly available, it needs an open-source license—otherwise nobody else is legally allowed to use / distribute / anything it. 

I recommend either the [MIT license](https://choosealicense.com/licenses/mit/) or [BSD 3-clause license](https://choosealicense.com/licenses/bsd-3-clause/), which should be included as a `LICENSE` file in the repo.

**Comment by anthony-walker** [comment]
License added.
